name: interval_timer
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.2
  flutter_bloc: ^5.0.1
  flutter_datetime_picker: ^1.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
