name: interval_timer
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  admob_flutter: ^1.0.0-beta.5
  app_review: ^1.1.2
  connectivity: '>=0.4.9 <2.0.0'
  equatable: ^1.2.2
  firebase_analytics: ^5.0.16
  firebase_core: ^0.4.5
  firebase_crashlytics: ^0.1.4+1
  flutter_bloc: ^5.0.1
  flutter_datetime_picker: ^1.3.8
  flutter_gradients: ^1.0.0+2
  flutter_icons: ^1.1.0
  fluttertoast: ^7.0.1+1
  get_it: ^4.0.2
  path: ^1.6.4
  path_provider: ^1.6.11
  shared_preferences: ^0.5.8
  url_launcher: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/launcher/icon.png"
  image_path_ios: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"